Copy this notebook and don't forget to **ADD YOUR NAME** in the name of the copy.

When you're done, save as a python notebook, and put it in the moodle space for LAB4 by next Wednesday evening:

## TODO1 : linear prediction in numpy

Suppose we have already learnt a multiclass classifier into 3 classes, with matrix weight W and bias vector b.

(below we just set them randomly, but suppose they are the result of a learning phase)

Suppose we have 4 input objects to classify (matrix X below).

Implement how to predict the class
- for the full batch X
- for a single row in X (take the first row)

Tip: look for the numpy argmax method

In [19]:
import numpy as np

# weight matrix and bias vector
W = np.random.rand(10,3)  # one column of weights per class
b = np.random.rand(3)     # one bias value per class

# 4 input vectors of size 10
X = np.random.rand(4,10)

In [20]:
# for the full_batch
Y = X @ W + b
pred = np.argmax(Y, axis=1)
pred

array([2, 1, 2, 1])

In [21]:
# for first row
Y_1 = X[0] @ W + b
pred_1 = np.argmax(Y_1)
pred_1

np.int64(2)

The scikit-learn python framework
Scikit-learn is a machine learning python library, which implements various regression, classification and clustering algorithms.

It's imported as sklearn.

Note sklearn is much used for linear and log-linear models, and less for deep learning.

The classification and regression parts on the home page both point to the same general page on supervised learning: https://scikit-learn.org/stable/supervised_learning.html#supervised-learning

Scikit-learn Vectorizers to get BOW vectors
In last lab we coded how to transform a collection of documents into matrices of "bag of words" representations of these documents (the X_train and X_test matrices of LAB2 and 3).

Scikit-learn has "vectorizer" methods to do that : https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

These matrices use the scipy.sparse type, which is appropriate for sparse matrices.

All the vectorizers modules have 3 methods:

fit : builds the vocabulary and the correspondance between word forms and word ids
transform : transforms the documents into matrices of counts
fit_transform : performs both actions

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
# a French corpus (to see what is going on with diacritics)
train_corpus = [
'Ceci est un document.',
"Aujourd'hui, ce document est à moi.",
'Et voilà le troisième.',
'Le premier document est-il le plus intéressant?',
]
vectorizer = CountVectorizer()
# the vectorizer is empty : this generates an error. but it is empty YET
#print(vectorizer.vocabulary_) # => AttributeError: 'CountVectorizer' object has no attribute 'vocabulary_'
#print(vectorizer.get_feature_names_out()) # => NotFittedError: Vocabulary not fitted or provided

The fit_transform method
Calling fit_transform on train_corpus will :

tokenize the text : it will split it into "words" using a regular expression to define what can be a separator between words
NB: this is a very uninformed and rough tokenization, meaning the obtained tokens are not always words as defined in linguistics
identify the vocabulary and associate an id to each element of the vocabulary
AND transform the training set into a matrix of BOW vectors

In [23]:
X_train = vectorizer.fit_transform(train_corpus)
# the matrix is sparse
print("type of X_train", type(X_train))
print("shape of X_train", X_train.shape)
print(X_train)
# here it is as a standard matrix
print(X_train.toarray())

type of X_train <class 'scipy.sparse._csr.csr_matrix'>
shape of X_train (4, 16)
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 21 stored elements and shape (4, 16)>
  Coords	Values
  (0, 2)	1
  (0, 4)	1
  (0, 14)	1
  (0, 3)	1
  (1, 4)	1
  (1, 3)	1
  (1, 0)	1
  (1, 6)	1
  (1, 1)	1
  (1, 10)	1
  (2, 5)	1
  (2, 15)	1
  (2, 9)	1
  (2, 13)	1
  (3, 4)	1
  (3, 3)	1
  (3, 9)	2
  (3, 12)	1
  (3, 7)	1
  (3, 11)	1
  (3, 8)	1
[[0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0]
 [1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1]
 [0 0 0 1 1 0 0 1 1 2 0 1 1 0 0 0]]


In [24]:
print(X_train[0])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (1, 16)>
  Coords	Values
  (0, 2)	1
  (0, 4)	1
  (0, 14)	1
  (0, 3)	1


In [25]:
# here is the mapping between word forms and ids (our "w2i" in previous lab ses
print(vectorizer.vocabulary_) # just in alphabetic order? so tokenize the whole text and for token in text assign a number to it starting from 0 BUT if we had a PAD that 0 would go there?
# the list of word forms (our i2w)
print(vectorizer.get_feature_names_out())

{'ceci': 2, 'est': 4, 'un': 14, 'document': 3, 'aujourd': 0, 'hui': 6, 'ce': 1, 'moi': 10, 'et': 5, 'voilà': 15, 'le': 9, 'troisième': 13, 'premier': 12, 'il': 7, 'plus': 11, 'intéressant': 8}
['aujourd' 'ce' 'ceci' 'document' 'est' 'et' 'hui' 'il' 'intéressant' 'le'
 'moi' 'plus' 'premier' 'troisième' 'un' 'voilà']


TODO2 : answer the following comprehension questions:
What is the size of the vocabulary
What does the 4th column of X.train.toarray() represent ?
What is printed when printing the sparse matrix ?

In [26]:
# What is the size of the vocabulary
print(len(vectorizer.vocabulary_)) # so CountVectorizer thinks there are 16 unique words in our 4 sentences
# What does the 4th column of X.train.toarray() represent ?
print(X_train.toarray()[:, 3]) # rows = sentences, columns = unique words; 4th column represents the appearance of 4th unique word across our corpus ('document'). indeed, est appears in all sentences but third, that is why the vector is [1 1 0 1]
# since the word 'ceci' appears in all sentenced but third too, it has the same structure
print(X_train.toarray()[:, 4])
# What is printed when printing the sparse matrix ?
X_train

16
[1 1 0 1]
[1 1 0 1]


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 21 stored elements and shape (4, 16)>

In [27]:
test_corpus = [ 'Ah un nouveau document.',
'Et ceci est encore un document.']
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(train_corpus)
X_test = vectorizer.transform(test_corpus)
print("shape of X_Train", X_train.shape)
print("shape of X_test", X_test.shape) # there are just 2 sentences in the test_corpus => 2 rows
print(X_test.toarray())
# 'document' is 3rd in the train_vocab and it appears in both sentences in test_corpus, that is why column 4 is (1, 1).
# 'ceci' is only in the 2nd sentence, that is why there is 1 in third column second row but not in the first row
print(vectorizer.vocabulary_) # it is the same, so those words that are in test_corpus but not in train_corpus are just not added

shape of X_Train (4, 16)
shape of X_test (2, 16)
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0]]
{'ceci': 2, 'est': 4, 'un': 14, 'document': 3, 'aujourd': 0, 'hui': 6, 'ce': 1, 'moi': 10, 'et': 5, 'voilà': 15, 'le': 9, 'troisième': 13, 'premier': 12, 'il': 7, 'plus': 11, 'intéressant': 8}


In [28]:
# What happened to the words in test_corpus that are not present in train_corpus?
# Compare to vectorizer.fit_transform
X_test = vectorizer.fit_transform(test_corpus)
print("shape of X_test: ", X_test.shape) # there are only 8 unique words in 2 sentences, that is why the shape is (2,8).
# if we use just transform, we take the vocabulary of uique words from train set
print(X_test.toarray())
print(vectorizer.vocabulary_) # here we built a new vocab based on test_corpus's unique words

shape of X_test:  (2, 8)
[[1 0 1 0 0 0 1 1]
 [0 1 1 1 1 1 0 1]]
{'ah': 0, 'un': 7, 'nouveau': 6, 'document': 2, 'et': 5, 'ceci': 1, 'est': 4, 'encore': 3}


TODO4: changing the parameters
We are now providing input sentences in which tokens have all been separated by spaces.

How can you change the tokenization that the CountVectorizer will use ? (see its constructor)
in particular, how can you make CountVectorizer split on spaces only?
Indications: study https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html to see all the members of the instance, and deduce which member to modify:

Find out which parameters to modify to switch to bigram and trigram of characters features, and print the obtained vocabulary - this means that the vocabulary will not be made of words, but of sequences of characters, of length 2 (character bigram) or 3 (character trigram)

Study the TfidfVectorizer class https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html and deduce how to easily obtain TF.IDF weigthed vector representations of the documents



In [29]:
# 1. How can you change the tokenization that the CountVectorizer will use ? (see its constructor)
# ==> here is the parameter that says what kind of tokenization we use token_pattern='(?u)\\b\\w\\w+\\b'
# ==> "The default regexp select tokens of 2 or more alphanumeric characters (punctuation is completely ignored and always treated as a token separator)."

In [30]:
# 2. in particular, how can you make CountVectorizer split on spaces only? Indications: study https://scikitlearn. org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html to see all the members of the instance, and deduce which member to modify:
# ==> token_pattern='[^ ]+'
vectorizer = CountVectorizer(token_pattern='[^ ]+')
X_test = vectorizer.fit_transform(train_corpus)
print(vectorizer.vocabulary_)
print(len(vectorizer.vocabulary_)) # 8 -> 17
# this is not really a good solution since punctuation symbols stick to words and 'document' and 'document.' are two different 'words'

{'ceci': 2, 'est': 5, 'un': 14, 'document.': 4, "aujourd'hui,": 0, 'ce': 1, 'document': 3, 'à': 16, 'moi.': 10, 'et': 7, 'voilà': 15, 'le': 9, 'troisième.': 13, 'premier': 12, 'est-il': 6, 'plus': 11, 'intéressant?': 8}
17


In [31]:
# 3. Find out which parameters to modify to switch to bigram and trigram of characters features, and print the obtained vocabulary - this means that the vocabulary will not be made of words, but of sequences of characters, of length 2 (character bigram) or 3 (character trigram)
# ==> there are parameters for that:
# ngram_rangetuple (min_n, max_n), default=(1, 1)
# The lower and upper boundary of the range of n-values for different word n-grams or char n-grams to be extracted. All values of n such such that min_n <= n <= max_n will be used. For example an ngram_range of (1, 1) means only unigrams, (1, 2) means unigrams and bigrams, and (2, 2) means only bigrams. Only applies if analyzer is not callable.
# analyzer{‘word’, ‘char’, ‘char_wb’} or callable, default=’word’
# Whether the feature should be made of word n-gram or character n-grams. Option ‘char_wb’ creates character n-grams only from text inside word boundaries; n-grams at the edges of words are padded with space. 

In [32]:
vectorizer = CountVectorizer(ngram_range=(2,3), analyzer='char')
X_test = vectorizer.fit_transform(test_corpus)
print(vectorizer.vocabulary_)
print(len(vectorizer.vocabulary_)) # this way we received a vocab of 77 unique combinations of 2 and 3 letters in our corpus


{'ah': 11, 'h ': 38, ' u': 9, 'un': 71, 'n ': 44, ' n': 7, 'no': 49, 'ou': 57, 'uv': 73, 've': 75, 'ea': 27, 'au': 13, 'u ': 67, ' d': 2, 'do': 23, 'oc': 53, 'cu': 21, 'um': 69, 'me': 42, 'en': 31, 'nt': 51, 't.': 66, 'ah ': 12, 'h u': 39, ' un': 10, 'un ': 72, 'n n': 46, ' no': 8, 'nou': 50, 'ouv': 58, 'uve': 74, 'vea': 76, 'eau': 28, 'au ': 14, 'u d': 68, ' do': 3, 'doc': 24, 'ocu': 54, 'cum': 22, 'ume': 70, 'men': 43, 'ent': 33, 'nt.': 52, 'et': 36, 't ': 63, ' c': 0, 'ce': 15, 'ec': 29, 'ci': 17, 'i ': 40, ' e': 4, 'es': 34, 'st': 61, 'nc': 47, 'co': 19, 'or': 55, 're': 59, 'e ': 25, 'et ': 37, 't c': 64, ' ce': 1, 'cec': 16, 'eci': 30, 'ci ': 18, 'i e': 41, ' es': 6, 'est': 35, 'st ': 62, 't e': 65, ' en': 5, 'enc': 32, 'nco': 48, 'cor': 20, 'ore': 56, 're ': 60, 'e u': 26, 'n d': 45}
77


In [ ]:
# Study the TfidfVectorizer class https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html and deduce how to easily obtain TF.IDF weigthed vector representations of the documents
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

array([[0.57615236, 0.        , 0.40993715, 0.        , 0.        ,
        0.        , 0.57615236, 0.40993715],
       [0.        , 0.44665616, 0.31779954, 0.44665616, 0.44665616,
        0.44665616, 0.        , 0.31779954]])

In [40]:
train_corpus = [
'Ceci est un document .',
"Aujourd'hui , ce document est encore un document à moi .",
'Et voilà le troisième .',
'Le premier document est -il le plus intéressant ?',
]
X_tfidf = vectorizer.fit_transform(train_corpus)
print("\nMEMBERS:\n", "\n".join([str(x) for x in vectorizer.__dict__.items()]))


MEMBERS:
 ('input', 'content')
('encoding', 'utf-8')
('decode_error', 'strict')
('strip_accents', None)
('preprocessor', None)
('tokenizer', None)
('analyzer', 'word')
('lowercase', True)
('token_pattern', '(?u)\\b\\w\\w+\\b')
('stop_words', None)
('max_df', 1.0)
('min_df', 1)
('max_features', None)
('ngram_range', (1, 1))
('vocabulary', None)
('binary', False)
('dtype', <class 'numpy.float64'>)
('norm', 'l2')
('use_idf', True)
('smooth_idf', True)
('sublinear_tf', False)
('_tfidf', TfidfTransformer())
('fixed_vocabulary_', False)
('_stop_words_id', 140731225928176)
('vocabulary_', {'ceci': 2, 'est': 5, 'un': 15, 'document': 3, 'aujourd': 0, 'hui': 7, 'ce': 1, 'encore': 4, 'moi': 11, 'et': 6, 'voilà': 16, 'le': 10, 'troisième': 14, 'premier': 13, 'il': 8, 'plus': 12, 'intéressant': 9})


In [50]:
import pandas as pd
X_tfidf = vectorizer.fit_transform(train_corpus)
terms = vectorizer.get_feature_names_out()
X_dense = X_tfidf.toarray()
df_tfidf = pd.DataFrame(X_dense, columns=terms)
df_tfidf

aujourd        ce      ceci  document    encore       est        et  \
0  0.000000  0.000000  0.640655  0.408922  0.000000  0.408922  0.000000   
1  0.361347  0.361347  0.000000  0.461286  0.361347  0.230643  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.525473   
3  0.000000  0.000000  0.000000  0.236221  0.000000  0.236221  0.000000   

        hui        il  intéressant        le       moi      plus   premier  \
0  0.000000  0.000000     0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.361347  0.000000     0.000000  0.000000  0.361347  0.000000  0.000000   
2  0.000000  0.000000     0.000000  0.414289  0.000000  0.000000  0.000000   
3  0.000000  0.370086     0.370086  0.583561  0.000000  0.370086  0.370086   

   troisième       un     voilà  
0   0.000000  0.50510  0.000000  
1   0.000000  0.28489  0.000000  
2   0.525473  0.00000  0.525473  
3   0.000000  0.00000  0.000000